apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/mnuttall/slim-devops-test-project:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/mnuttall/slim-devops-test-project:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: slim-devops-test-project
        chartPath: charts/slim-devops-test-project
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/mnuttall/slim-devops-test-project"
          image.tag: "{{.TAG}}"
